// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID         int64     `json:"id"`
	ClientName string    `json:"client_name"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
}

type Project struct {
	ID          int64     `json:"id"`
	ProjectName string    `json:"project_name"`
	ClientID    int64     `json:"client_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type ProjectTeam struct {
	ID        int64     `json:"id"`
	ProjectID int64     `json:"project_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Sbus struct {
	ID            int64       `json:"id"`
	SbuName       pgtype.Text `json:"sbu_name"`
	SbuHeadUserID pgtype.Int8 `json:"sbu_head_user_id"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Task struct {
	ID             int64     `json:"id"`
	TaskTitle      string    `json:"task_title"`
	Progress       int64     `json:"progress"`
	ProjectID      int64     `json:"project_id"`
	AssignedUserID int64     `json:"assigned_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type User struct {
	ID         int64       `json:"id"`
	Firstname  string      `json:"firstname"`
	Lastname   string      `json:"lastname"`
	Email      string      `json:"email"`
	Password   string      `json:"password"`
	UserRoleID pgtype.Int8 `json:"user_role_id"`
	SbuID      pgtype.Int8 `json:"sbu_id"`
	CreatedAt  time.Time   `json:"created_at"`
}

type UserRole struct {
	ID        int64     `json:"id"`
	RoleName  string    `json:"role_name"`
	CreatedAt time.Time `json:"created_at"`
}
